version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: browserslist
    versions:
    - 4.16.1
    - 4.16.3
    - 4.16.4
  - dependency-name: release-it
    versions:
    - 14.2.2
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
    - 1.11.2
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
    - 3.25.3
  - dependency-name: launchdarkly-js-client-sdk
    versions:
    - 2.19.0
  - dependency-name: event-source-polyfill
    versions:
    - 1.0.22
  - dependency-name: ember-prism
    versions:
    - 0.9.0
